### PR TITLE
API in masthead is now a menu with links to the API docs and the pyth…

### PR DESCRIPTION
**Pull request by emepyc**
…on client

### CODE REVIEW

**Comment by emepyc** [comment]
I don't particularly like the change in app/js/directives.js, but I don't see any other way to ignore the "target" when it is not specified in the config file. Any ideas @LucaFumis ?

**Comment by LucaFumis** [comment]
Hi Miguel,
yeah, I see what you mean. the only solution I can think of is to drop the `ng-if` altogether and have a default target, but I think that might force an Angular reload...
Something like this perhaps (untested)?
```<a target={{subitem.target || "self"}} href="{{subitem.href}}">{{subitem.label}}</a>```

**Comment by LucaFumis** [comment]
Or perhaps
```target={{subitem.target || ""}}```
again not sure how reliable that is... seems to work at first...

**Comment by emepyc** [comment]
That's exactly what I tried before going for the committed solution :-(
I suppose it doesn't matter to end up with an empty target (chrome omits it, ie, it has the expected behaviour), but I don't feel comfortable relying on that

**Comment by emepyc** [comment]
I mean, target="" is probably unspecified (which means that it may be up to the browser brand to do whatever they want)

**Comment by emepyc** [comment]
the other option is to add
```
target: _self
```
in all the other links in the config file

**Pull request merged**
