### PR TITLE
working with current live.json config file

### PR DESCRIPTION
**Pull request by emepyc**
We need a way to enable webapp config parameters being read live at load time. Two use cases:

1.- We want to test the webapp with a different rest api version than the one hardcoded. In a kubernetes cluster we can mount live a different version of the api via the config file

2.- We want to enable and disable features in the master branch so we don't need to wait for a fully working/complete feature to be merged into master

### CODE REVIEW

**Comment by LucaFumis** [comment]
Ciao Miguel, getting familiar with these pull requests:
just above here Git says the branch has conflicts... but I'd imagine that's a Git problem?

**Comment by LucaFumis** [comment]
Also, just out of curiosity really, was this config different from the other configuration being loaded (I mean requirements for the implementation)?

**Comment by emepyc** [comment]
Thanks Luca. It was clean (no conflicts) when I made the PR, but when I merged batchSearchSupport one conflict arouse.
I have now fixed it

**Comment by emepyc** [comment]
And for the difference between both config files, the difference is subtle :-(
Mainly, default.json and custom.json are merged at build time. What Eliseo needs is a config file that _can_ be mounted when the container is deployed (and have different config files in different clusters).
Suppose the webapp container is deployed in two different clusters in the google cloud: A and B and in the B cluster we want to test a different version of the API. He needs a way to mount a config file in the cluster B that tells to the api service which version to use.
I can't think of a way to use default.json/custom.js current mechanism to meet this use case (the merge happens at build time. You can mount a replacement for that file but you need to know its contents in advance to avoid missing any other parameter.

I don't know how many times we will need this, but Eliseo was very enthusiastic about it.

I also wanted to have a mechanism to switch on and off new features in master via a config file. We can use any of both for this.
The rationale here is to allow having not fully working features in feature branches before merging into master. Merges can happen more frequently (so PRs are also lighter) but we keep the features "off" until they are functional and testable in beta.

**Comment by emepyc** [comment]
For example, I may be able to make a PR for batch-search in an immature state if the feature is switched off in the master live.json config file.
"Switch off" meaning (in that case) that the link to the batch search page from the home page is only shown in the feature is "on" in the config file.

For the _filter_by_target_list_ "switch off" could mean that the part of the template that includes the upload buttom is hidden if the feature is off in the config file.

We can discuss all this tomorrow

**Comment by LucaFumis** [comment]
Thank you for explaining that Miguel.
Now that me and Rippa have both approved the changes, it's ok to merge, right? 
I take either one of us can merge?

**Comment by emepyc** [comment]
Yes, any of you can merge and remove the branch
Thanks!

**Pull request merged**
